<a href="https://colab.research.google.com/github/harshvgangawane/PWSA4/blob/main/PWSA8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np #importing numpy library

In [5]:
a=np.random.randint(1,100,(3,3))

In [6]:
a

array([[84, 50, 84],
       [13, 26,  2],
       [30, 73, 69]])

In [7]:
b=np.arange(1,11)
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
b.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [9]:
b.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [10]:
r=np.random.rand(4,4)

In [11]:
r

array([[0.05117374, 0.67927445, 0.90600848, 0.85222839],
       [0.54854343, 0.92963625, 0.5028672 , 0.28934023],
       [0.18296376, 0.72562096, 0.65650091, 0.87338456],
       [0.06459143, 0.94340108, 0.51113557, 0.47743069]])

In [12]:
s=np.zeros((6,6))

In [13]:
s

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [14]:
s[1:5,1:5]=r

In [15]:
s

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.05117374, 0.67927445, 0.90600848, 0.85222839,
        0.        ],
       [0.        , 0.54854343, 0.92963625, 0.5028672 , 0.28934023,
        0.        ],
       [0.        , 0.18296376, 0.72562096, 0.65650091, 0.87338456,
        0.        ],
       [0.        , 0.06459143, 0.94340108, 0.51113557, 0.47743069,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ]])

In [16]:
p=np.arange(10,60,5)

In [17]:
p

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55])

In [18]:
e=np.array(['Python','numpy','pandas'])

In [19]:
e

array(['Python', 'numpy', 'pandas'], dtype='<U6')

In [20]:
np.char.upper(e)

array(['PYTHON', 'NUMPY', 'PANDAS'], dtype='<U6')

In [21]:
np.char.lower(e)

array(['python', 'numpy', 'pandas'], dtype='<U6')

In [22]:
np.char.capitalize(e)

array(['Python', 'Numpy', 'Pandas'], dtype='<U6')

In [23]:
np.char.title(e)

array(['Python', 'Numpy', 'Pandas'], dtype='<U6')

In [24]:
r1=np.array(['Python','numpy','pandas'])
r1

array(['Python', 'numpy', 'pandas'], dtype='<U6')

In [65]:
words = np.char.join(' ', r1)



In [66]:
print("\nArray of Words with Spaces:\n",words)


Array of Words with Spaces:
 ['P y t h o n' 'n u m p y' 'p a n d a s']


In [25]:
m1=np.random.randint(1,10,(2,2))
m2=m1=np.random.randint(1,8,(2,2))

In [26]:
m1

array([[5, 7],
       [7, 3]])

In [27]:
m2

array([[5, 7],
       [7, 3]])

In [29]:
m1+m2

array([[10, 14],
       [14,  6]])

In [30]:
m1-m2

array([[0, 0],
       [0, 0]])

In [31]:
m1*m2

array([[25, 49],
       [49,  9]])

In [32]:
m1/m2

array([[1., 1.],
       [1., 1.]])

In [33]:
m7=np.random.randint(1,10,(5,5))

In [34]:
m7

array([[6, 4, 4, 2, 4],
       [6, 9, 5, 6, 4],
       [1, 8, 4, 1, 2],
       [6, 8, 9, 9, 8],
       [4, 4, 9, 8, 5]])

In [35]:
m7=np.eye(m7.shape[0])
m7

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [39]:
n7=np.random.randint(0,1001,(5,5))

In [40]:
n7

array([[308, 531, 512, 272, 146],
       [674,   7,  91, 976, 166],
       [ 69,  67, 156, 946, 872],
       [938, 692, 424, 724, 371],
       [551, 897, 462, 295, 753]])

In [58]:
n8 = np.random.randint(0, 1001, 100)

# Function to check if a number is prime
def is_prime(num):
    if num < 2:
        return False
    for i in range(2, int(num**0.5) + 1):
        if num % i == 0:
            return False
    return True

In [59]:
prime_numbers = [num for num in n8 if is_prime(num)]
print("\nPrime Numbers in Array:\n", prime_numbers)


Prime Numbers in Array:
 [743, 41, 569, 499, 379, 983, 673, 347, 41, 211, 601, 181, 857, 29, 727]


In [ ]:
import numpy as np
daily_temperatures = np.random.uniform(15, 30, 30)

weekly_temperatures = np.zeros((5, 7))  # 5 weeks to accommodate 30 days
weekly_temperatures[:4, :] = daily_temperatures[:28].reshape(4, 7)
weekly_temperatures[4, :2] = daily_temperatures[28:]  # Last week has 2 days

weekly_averages = np.mean(weekly_temperatures, axis=1)

print("Daily Temperatures for the Month:\n", daily_temperatures)
print("\nWeekly Temperatures:\n", weekly_temperatures)
print("\nWeekly Averages:\n", weekly_averages)
